name: Publish
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install and build
        working-directory: ./ui
        run: |
          yarn --frozen-lockfile
          yarn
          patch node_modules/@observablehq/framework/dist/duckdb.js ddb_132.patch
          yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ui/dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
